SELECT DISTINCT INCORPORATION_NUMBER
FROM CORPORATE_BODY cb
         INNER JOIN INSOLVENCY_CASE ic on cb.CORPORATE_BODY_ID = ic.CORPORATE_BODY_ID
WHERE ACTION_CODE_TYPE_ID = 7305
  AND INSOLVENCY_CASE_TYPE_ID = 7
  AND INSOLVENCY_CASE_END_DATE > SYSDATE
union
SELECT DISTINCT INCORPORATION_NUMBER
FROM CORPORATE_BODY cb
         INNER JOIN INSOLVENCY_CASE  ic ON cb.CORPORATE_BODY_ID = ic.CORPORATE_BODY_ID
WHERE INSOLVENCY_CASE_TYPE_ID = 13
  AND INSOLVENCY_CASE_END_DATE > SYSDATE