SELECT CB.INCORPORATION_NUMBER AS INCORPORATION_NUMBER
FROM CORPORATE_BODY CB
WHERE EXISTS(SELECT 1
             FROM INSOLVENCY_CASE IC
             WHERE CB.CORPORATE_BODY_ID = IC.CORPORATE_BODY_ID
               AND IC.INSOLVENCY_CASE_END_DATE > SYSDATE
               AND (IC.INSOLVENCY_CASE_TYPE_ID = 13
                 OR IC.INSOLVENCY_CASE_TYPE_ID = 7 AND CB.ACTION_CODE_TYPE_ID = 7305))
