SELECT CB.INCORPORATION_NUMBER AS INCORPORATION_NUMBER
FROM CORPORATE_BODY CB
WHERE CB.TRADING_STATUS_TYPE_ID = 5
  AND CB.ACTION_CODE_DATE >= TO_DATE('30-DEC-2009', 'DD-MON-YYYY')
  AND (SUBSTR(CB.INCORPORATION_NUMBER, 1, 2) != 'SE'
    OR SUBSTR(CB.INCORPORATION_NUMBER, 1, 2) = 'SE' AND CB.TRADING_STATUS_SUB_TYPE_ID = 3
    OR CB.ACTION_CODE_TYPE_ID = 9100 AND CB.TRADING_STATUS_SUB_TYPE_ID = 2)
