SELECT INCORPORATION_NUMBER
FROM CORPORATE_BODY
WHERE ACTION_CODE_TYPE_ID=7404
UNION
SELECT DISTINCT INCORPORATION_NUMBER
FROM chipstab.CORPORATE_BODY CB
         INNER JOIN INSOLVENCY_CASE IC ON CB.CORPORATE_BODY_ID = IC.CORPORATE_BODY_ID
WHERE ACTION_CODE_TYPE_ID = 7701
  AND INSOLVENCY_CASE_TYPE_ID = 13
  AND INSOLVENCY_CASE_END_DATE > SYSDATE
  AND EXISTS (SELECT * FROM INSOLVENCY_CASE IC2
              where IC2.CORPORATE_BODY_ID = CB.CORPORATE_BODY_ID
                AND INSOLVENCY_CASE_TYPE_ID IN (5,6,16)
                AND INSOLVENCY_CASE_END_DATE > SYSDATE)
  AND SUBSTR (INCORPORATION_NUMBER, 1, 2) IN ('SC','SA','SF','SL','SZ','SP','SO','SR', 'GS' )
UNION
SELECT DISTINCT CB.INCORPORATION_NUMBER
FROM CORPORATE_BODY CB
         INNER JOIN INSOLVENCY_CASE IC ON CB.CORPORATE_BODY_ID = IC.CORPORATE_BODY_ID
WHERE ACTION_CODE_TYPE_ID = 7701
  AND INSOLVENCY_CASE_TYPE_ID = 8
  AND INSOLVENCY_CASE_END_DATE > SYSDATE
  AND EXISTS (SELECT * FROM INSOLVENCY_CASE IC2
              WHERE IC2.CORPORATE_BODY_ID = CB.CORPORATE_BODY_ID
                AND INSOLVENCY_CASE_TYPE_ID IN (5,6,16)
                AND INSOLVENCY_CASE_END_DATE > SYSDATE)
  AND SUBSTR (INCORPORATION_NUMBER, 1, 2) IN ('SC','SA','SF','SL','SZ','SP','SO','SR', 'GS' )
UNION
SELECT DISTINCT CB.INCORPORATION_NUMBER
FROM CORPORATE_BODY CB
         INNER JOIN INSOLVENCY_CASE IC ON CB.CORPORATE_BODY_ID = IC.CORPORATE_BODY_ID
WHERE ACTION_CODE_TYPE_ID = 7701
  AND INSOLVENCY_CASE_TYPE_ID = 7
  AND INSOLVENCY_CASE_END_DATE > SYSDATE
  AND EXISTS (SELECT * FROM INSOLVENCY_CASE IC2
              WHERE IC2.CORPORATE_BODY_ID = CB.CORPORATE_BODY_ID
                AND INSOLVENCY_CASE_TYPE_ID IN (5,6,16)
                AND INSOLVENCY_CASE_END_DATE > SYSDATE)
  AND SUBSTR (INCORPORATION_NUMBER, 1, 2) IN ('SC','SA','SF','SL','SZ','SP','SO','SR', 'GS' )
UNION
SELECT DISTINCT CB.INCORPORATION_NUMBER
FROM CORPORATE_BODY CB
         INNER JOIN INSOLVENCY_CASE IC ON CB.CORPORATE_BODY_ID = IC.CORPORATE_BODY_ID
WHERE ACTION_CODE_TYPE_ID = 7701
  AND INSOLVENCY_CASE_TYPE_ID = 5
  AND INSOLVENCY_CASE_END_DATE > SYSDATE
  AND EXISTS (SELECT * FROM INSOLVENCY_CASE IC2
              WHERE IC2.CORPORATE_BODY_ID = CB.CORPORATE_BODY_ID
                AND INSOLVENCY_CASE_TYPE_ID = 13
                AND INSOLVENCY_CASE_END_DATE > SYSDATE)
  AND EXISTS (SELECT * FROM INSOLVENCY_CASE IC3
              WHERE IC3.CORPORATE_BODY_ID = CB.CORPORATE_BODY_ID
                AND INSOLVENCY_CASE_TYPE_ID IN (6,16)
                AND INSOLVENCY_CASE_END_DATE > SYSDATE)
  AND SUBSTR (INCORPORATION_NUMBER, 1, 2) NOT IN ('SC','SA','SF','SL','SZ','SP','SO','SR', 'GS' )
UNION
SELECT DISTINCT CB.INCORPORATION_NUMBER
FROM CORPORATE_BODY CB
         INNER JOIN INSOLVENCY_CASE IC ON CB.CORPORATE_BODY_ID = IC.CORPORATE_BODY_ID
WHERE ACTION_CODE_TYPE_ID = 7701
  AND INSOLVENCY_CASE_TYPE_ID = 5
  AND INSOLVENCY_CASE_END_DATE > SYSDATE
  AND EXISTS (SELECT * FROM INSOLVENCY_CASE IC2
              WHERE IC2.CORPORATE_BODY_ID = CB.CORPORATE_BODY_ID
                AND INSOLVENCY_CASE_TYPE_ID = 8
                AND INSOLVENCY_CASE_END_DATE > SYSDATE)
  AND EXISTS (SELECT * FROM INSOLVENCY_CASE IC3
              WHERE IC3.CORPORATE_BODY_ID = CB.CORPORATE_BODY_ID
                AND INSOLVENCY_CASE_TYPE_ID IN (6,16)
                AND INSOLVENCY_CASE_END_DATE > SYSDATE)
  AND SUBSTR (INCORPORATION_NUMBER, 1, 2) NOT IN ('SC','SA','SF','SL','SZ','SP','SO','SR', 'GS' )
UNION
SELECT DISTINCT CB.INCORPORATION_NUMBER
FROM CORPORATE_BODY CB
         INNER JOIN INSOLVENCY_CASE IC ON CB.CORPORATE_BODY_ID = IC.CORPORATE_BODY_ID
WHERE ACTION_CODE_TYPE_ID = 7701
  AND INSOLVENCY_CASE_TYPE_ID = 5
  AND INSOLVENCY_CASE_END_DATE > SYSDATE
  AND EXISTS (SELECT * FROM INSOLVENCY_CASE IC2
              WHERE IC2.CORPORATE_BODY_ID = CB.CORPORATE_BODY_ID
                AND INSOLVENCY_CASE_TYPE_ID = 6
                AND INSOLVENCY_CASE_END_DATE > SYSDATE)
  AND EXISTS (SELECT * FROM INSOLVENCY_CASE IC3
              WHERE IC3.CORPORATE_BODY_ID = CB.CORPORATE_BODY_ID
                AND INSOLVENCY_CASE_TYPE_ID = 7
                AND INSOLVENCY_CASE_END_DATE > SYSDATE)
  AND SUBSTR (INCORPORATION_NUMBER, 1, 2) NOT IN ('SC','SA','SF','SL','SZ','SP','SO','SR', 'GS' )
UNION
SELECT DISTINCT CB.INCORPORATION_NUMBER
FROM CORPORATE_BODY CB
         INNER JOIN INSOLVENCY_CASE IC ON CB.CORPORATE_BODY_ID = IC.CORPORATE_BODY_ID
WHERE ACTION_CODE_TYPE_ID = 7701
  AND INSOLVENCY_CASE_TYPE_ID = 5
  AND INSOLVENCY_CASE_END_DATE > SYSDATE
  AND EXISTS (SELECT * FROM INSOLVENCY_CASE IC2
              WHERE IC2.CORPORATE_BODY_ID = CB.CORPORATE_BODY_ID
                AND INSOLVENCY_CASE_TYPE_ID IN (6,16)
                AND INSOLVENCY_CASE_END_DATE > SYSDATE)
  AND SUBSTR (INCORPORATION_NUMBER, 1, 2) NOT IN ('SC','SA','SF','SL','SZ','SP','SO','SR', 'GS')
UNION
SELECT DISTINCT CB.INCORPORATION_NUMBER
FROM CORPORATE_BODY CB
         INNER JOIN INSOLVENCY_CASE IC ON CB.CORPORATE_BODY_ID = IC.CORPORATE_BODY_ID
WHERE ACTION_CODE_TYPE_ID = 7701
  AND INSOLVENCY_CASE_TYPE_ID = 8
  AND INSOLVENCY_CASE_END_DATE > SYSDATE
  AND EXISTS (SELECT * FROM INSOLVENCY_CASE IC2
              WHERE IC2.CORPORATE_BODY_ID = CB.CORPORATE_BODY_ID
                AND INSOLVENCY_CASE_TYPE_ID IN (6,16)
                AND INSOLVENCY_CASE_END_DATE > SYSDATE)
  AND SUBSTR (INCORPORATION_NUMBER, 1, 2) NOT IN ('SC','SA','SF','SL','SZ','SP','SO','SR', 'GS')
    UNION
SELECT DISTINCT CB.INCORPORATION_NUMBER
FROM CORPORATE_BODY CB
         INNER JOIN INSOLVENCY_CASE IC ON CB.CORPORATE_BODY_ID = IC.CORPORATE_BODY_ID
WHERE ACTION_CODE_TYPE_ID = 7701
  AND INSOLVENCY_CASE_TYPE_ID = 7
  AND INSOLVENCY_CASE_END_DATE > SYSDATE
  AND EXISTS (SELECT * FROM INSOLVENCY_CASE IC2
              WHERE IC2.CORPORATE_BODY_ID = CB.CORPORATE_BODY_ID
                AND INSOLVENCY_CASE_TYPE_ID IN (6,16)
                AND INSOLVENCY_CASE_END_DATE > SYSDATE)
  AND SUBSTR (INCORPORATION_NUMBER, 1, 2) NOT IN ('SC','SA','SF','SL','SZ','SP','SO','SR', 'GS')
UNION
SELECT DISTINCT CB.INCORPORATION_NUMBER
FROM CORPORATE_BODY CB
         INNER JOIN INSOLVENCY_CASE IC ON CB.CORPORATE_BODY_ID = IC.CORPORATE_BODY_ID
WHERE ACTION_CODE_TYPE_ID = 7701
  AND INSOLVENCY_CASE_TYPE_ID = 13
  AND INSOLVENCY_CASE_END_DATE > SYSDATE
  AND EXISTS (SELECT * FROM INSOLVENCY_CASE IC2
              WHERE IC2.CORPORATE_BODY_ID = CB.CORPORATE_BODY_ID
                AND INSOLVENCY_CASE_TYPE_ID IN (6,16)
                AND INSOLVENCY_CASE_END_DATE > SYSDATE)
UNION
SELECT DISTINCT CB.INCORPORATION_NUMBER
FROM CORPORATE_BODY CB
         INNER JOIN INSOLVENCY_CASE IC ON CB.CORPORATE_BODY_ID = IC.CORPORATE_BODY_ID
WHERE ACTION_CODE_TYPE_ID = 7701
  AND INSOLVENCY_CASE_TYPE_ID = 8
  AND INSOLVENCY_CASE_END_DATE > SYSDATE
  AND EXISTS (SELECT * FROM INSOLVENCY_CASE IC2
              WHERE IC2.CORPORATE_BODY_ID = CB.CORPORATE_BODY_ID
                AND INSOLVENCY_CASE_TYPE_ID = 5
                AND INSOLVENCY_CASE_END_DATE > SYSDATE)
  AND SUBSTR (INCORPORATION_NUMBER, 1, 2) NOT IN ('SC','SA','SF','SL','SZ','SP','SO','SR', 'GS')
UNION
SELECT DISTINCT CB.INCORPORATION_NUMBER
FROM CORPORATE_BODY CB
         INNER JOIN INSOLVENCY_CASE IC ON CB.CORPORATE_BODY_ID = IC.CORPORATE_BODY_ID
WHERE ACTION_CODE_TYPE_ID = 7701
  AND INSOLVENCY_CASE_TYPE_ID = 5
  AND INSOLVENCY_CASE_END_DATE > SYSDATE
  AND EXISTS (SELECT * FROM INSOLVENCY_CASE IC2
              WHERE IC2.CORPORATE_BODY_ID = CB.CORPORATE_BODY_ID
                AND INSOLVENCY_CASE_TYPE_ID = 7
                AND INSOLVENCY_CASE_END_DATE > SYSDATE)
  AND SUBSTR (INCORPORATION_NUMBER, 1, 2) NOT IN ('SC','SA','SF','SL','SZ','SP','SO','SR', 'GS')
UNION
SELECT DISTINCT CB.INCORPORATION_NUMBER
FROM CORPORATE_BODY CB
         INNER JOIN INSOLVENCY_CASE IC ON CB.CORPORATE_BODY_ID = IC.CORPORATE_BODY_ID
WHERE ACTION_CODE_TYPE_ID = 7701
  AND INSOLVENCY_CASE_TYPE_ID = 5
  AND EXISTS (SELECT * FROM INSOLVENCY_CASE IC2
              WHERE IC2.CORPORATE_BODY_ID = CB.CORPORATE_BODY_ID
                AND INSOLVENCY_CASE_TYPE_ID = 13)
  AND SUBSTR (INCORPORATION_NUMBER, 1, 2) NOT IN ('SC','SA','SF','SL','SZ','SP','SO','SR', 'GS')
  AND INSOLVENCY_CASE_END_DATE > SYSDATE





