SELECT CB.INCORPORATION_NUMBER AS INCORPORATION_NUMBER
FROM CORPORATE_BODY CB
WHERE CB.ACTION_CODE_TYPE_ID = 7404
   OR CB.ACTION_CODE_TYPE_ID = 7701
    AND
      EXISTS(SELECT 1
             FROM INSOLVENCY_CASE IC
             WHERE IC.CORPORATE_BODY_ID = CB.CORPORATE_BODY_ID
               AND IC.INSOLVENCY_CASE_TYPE_ID IN (5, 6, 16)
               AND IC.INSOLVENCY_CASE_END_DATE > SYSDATE)
    AND
      EXISTS(SELECT 1
             FROM INSOLVENCY_CASE IC
             WHERE IC.CORPORATE_BODY_ID = CB.CORPORATE_BODY_ID
               AND IC.INSOLVENCY_CASE_TYPE_ID IN (7, 8, 13)
               AND IC.INSOLVENCY_CASE_END_DATE > SYSDATE)
   OR SUBSTR(CB.INCORPORATION_NUMBER, 1, 2) NOT IN ('SC', 'SA', 'SF', 'SL', 'SZ', 'SP', 'SO', 'SR', 'GS')
    AND EXISTS(SELECT 1
               FROM INSOLVENCY_CASE IC
               WHERE IC.CORPORATE_BODY_ID = CB.CORPORATE_BODY_ID
                 AND IC.INSOLVENCY_CASE_TYPE_ID = 5
                 AND IC.INSOLVENCY_CASE_END_DATE > SYSDATE)
    AND EXISTS(SELECT 1
               FROM INSOLVENCY_CASE IC
               WHERE IC.CORPORATE_BODY_ID = CB.CORPORATE_BODY_ID
                 AND IC.INSOLVENCY_CASE_TYPE_ID IN (6, 16)
                 AND IC.INSOLVENCY_CASE_END_DATE > SYSDATE)