SELECT CB.INCORPORATION_NUMBER AS INCORPORATION_NUMBER
FROM CORPORATE_BODY CB
WHERE CB.ACTION_CODE_TYPE_ID IN (7001, 7002, 7101, 7401, 7402, 7403)
   OR CB.ACTION_CODE_TYPE_ID = 7701
    AND EXISTS(SELECT 1
               FROM INSOLVENCY_CASE IC
               WHERE CB.CORPORATE_BODY_ID = IC.CORPORATE_BODY_ID
                 AND INSOLVENCY_CASE_END_DATE > SYSDATE
                 AND INSOLVENCY_CASE_TYPE_ID IN (1, 2, 3))