SELECT DISTINCT INCORPORATION_NUMBER
FROM CORPORATE_BODY cb
         INNER JOIN insolvency_case ic on cb.corporate_body_id = ic.corporate_body_id
WHERE ACTION_CODE_TYPE_ID IN (7301,7302)
  AND INSOLVENCY_CASE_TYPE_ID IN (5, 6, 16)
  AND SUBSTR (INCORPORATION_NUMBER, 1, 2) IN ('SC','SA','SF','SL','SZ','SP','SO','SR', 'GS' )
  AND INSOLVENCY_CASE_END_DATE > SYSDATE
UNION
SELECT DISTINCT INCORPORATION_NUMBER
FROM CORPORATE_BODY cb
         INNER JOIN INSOLVENCY_CASE  ic ON cb.CORPORATE_BODY_ID = ic.CORPORATE_BODY_ID
WHERE ACTION_CODE_TYPE_ID = 7301
  AND INSOLVENCY_CASE_TYPE_ID = 5
  AND SUBSTR (INCORPORATION_NUMBER, 1, 2) NOT IN ('SC','SA','SF','SL','SZ','SP','SO','SR', 'GS' )
  AND INSOLVENCY_CASE_END_DATE > SYSDATE
UNION
SELECT DISTINCT INCORPORATION_NUMBER
FROM CORPORATE_BODY cb
         INNER JOIN INSOLVENCY_CASE  ic ON cb.CORPORATE_BODY_ID = ic.CORPORATE_BODY_ID
WHERE ACTION_CODE_TYPE_ID = 7302
  AND INSOLVENCY_CASE_TYPE_ID IN (6,16)
  AND SUBSTR (INCORPORATION_NUMBER, 1, 2) NOT IN ('SC','SA','SF','SL','SZ','SP','SO','SR', 'GS' )
  AND INSOLVENCY_CASE_END_DATE > SYSDATE
UNION
SELECT DISTINCT INCORPORATION_NUMBER
FROM CORPORATE_BODY cb
         INNER JOIN INSOLVENCY_CASE  ic ON cb.CORPORATE_BODY_ID = ic.CORPORATE_BODY_ID
WHERE ACTION_CODE_TYPE_ID = 7701
  AND INSOLVENCY_CASE_TYPE_ID IN (5,6,16)
  AND SUBSTR (INCORPORATION_NUMBER, 1, 2) NOT IN ('SC','SA','SF','SL','SZ','SP','SO','SR', 'GS' )
  AND INSOLVENCY_CASE_END_DATE > SYSDATE
UNION
SELECT DISTINCT INCORPORATION_NUMBER
FROM CORPORATE_BODY cb
         INNER JOIN INSOLVENCY_CASE ic ON cb.CORPORATE_BODY_ID = ic.CORPORATE_BODY_ID
WHERE action_code_type_id = 7701
  AND INSOLVENCY_CASE_TYPE_ID IN (5,6,16)
  AND SUBSTR (INCORPORATION_NUMBER, 1, 2) IN ('SC','SA','SF','SL','SZ','SP','SO','SR', 'GS' )
  AND INSOLVENCY_CASE_END_DATE > SYSDATE
