SELECT CB.INCORPORATION_NUMBER AS INCORPORATION_NUMBER
FROM CORPORATE_BODY CB
WHERE EXISTS(SELECT 1
             FROM INSOLVENCY_CASE IC
             WHERE CB.CORPORATE_BODY_ID = IC.CORPORATE_BODY_ID
               AND (CB.ACTION_CODE_TYPE_ID = 7301 AND IC.INSOLVENCY_CASE_TYPE_ID = 5
                 OR CB.ACTION_CODE_TYPE_ID = 7302 AND IC.INSOLVENCY_CASE_TYPE_ID IN (6, 16)
                 OR CB.ACTION_CODE_TYPE_ID = 7701 AND IC.INSOLVENCY_CASE_TYPE_ID IN (5, 6, 16)))
   OR SUBSTR(CB.INCORPORATION_NUMBER, 1, 2) IN ('SC', 'SA', 'SF', 'SL', 'SZ', 'SP', 'SO', 'SR', 'GS')
    AND EXISTS(SELECT 1
               FROM INSOLVENCY_CASE IC
               WHERE CB.CORPORATE_BODY_ID = IC.CORPORATE_BODY_ID
                 AND (CB.ACTION_CODE_TYPE_ID = 7301 AND IC.INSOLVENCY_CASE_TYPE_ID IN (6, 16)
                   OR CB.ACTION_CODE_TYPE_ID = 7302 AND IC.INSOLVENCY_CASE_TYPE_ID = 5))
