SELECT INCORPORATION_NUMBER
FROM CORPORATE_BODY CB
WHERE CB.TRADING_STATUS_TYPE_ID IN (1, 2)
   OR CB.ACTION_CODE_DATE >= TO_DATE('20100101', 'YYYYMMDD') AND CB.ACTION_CODE_TYPE_ID >= 9000
   OR EXISTS(SELECT 1
             FROM TRANSACTION TRANS
             WHERE TRANS.CORPORATE_BODY_ID = CB.CORPORATE_BODY_ID
               AND TRANS.TRANSACTION_TYPE_ID IN (541, 542)
               AND TRANS.TRANSACTION_STATUS_TYPE_ID = 9
               AND TRANS.TRANSACTION_STATUS_DATE = TO_DATE('05/01/2010', 'DD/MM/YYYY'))
